theme: jekyll-theme-minimal
title: gwenshiro's portfolio
description: bookmark this to keep an eye on my on-going projects!
logo: https://scontent-sin2-1.xx.fbcdn.net/v/t1.0-9/47578166_2396642430349458_17669272117444608_n.jpg?_nc_cat=110&_nc_eui2=AeGS5ATR6m1dJQPpUZqAct_odxFWWTQEtpR7FRPPzV161pycUhIoqS3hFaAttRGPD8CDCHId8DBK6FLstyURbINWPPbOb16UjiaTKkF3--bS6w&_nc_ht=scontent-sin2-1.xx&oh=472b02a5d655b3b2309df1f7f7fd2d3c&oe=5C696CE7
show_downloads: true
